# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
# - 3.1 - skip until updated glue on CRAN
- 3.2
- oldrel
- release
- devel

before_script:
- psql -c 'create database test;' -U postgres

after_success:
  - Rscript -e 'covr::codecov()'

